package com.myspace.tmlpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "TMLPOC")
public class Hello extends org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "HELLO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "HELLO_ID_SEQ", name = "HELLO_ID_GENERATOR")


	private java.lang.Long id;

	private java.lang.String test1;

	private java.lang.String test2;

	private java.lang.Integer test3;

	public Hello() {
	}

	@Override
	public String toString() {
		return "Hello [id=" + id + ", test1=" + test1 + ", test2=" + test2 + ", test3=" + test3 + "]";
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getTest1() {
		return this.test1;
	}

	public void setTest1(java.lang.String test1) {
		this.test1 = test1;
	}

	public java.lang.String getTest2() {
		return this.test2;
	}

	public void setTest2(java.lang.String test2) {
		this.test2 = test2;
	}

	public java.lang.Integer getTest3() {
		return this.test3;
	}

	public void setTest3(java.lang.Integer test3) {
		this.test3 = test3;
	}

	public Hello(java.lang.Long id, java.lang.String test1,
			java.lang.String test2, java.lang.Integer test3) {
		this.id = id;
		this.test1 = test1;
		this.test2 = test2;
		this.test3 = test3;
	}

}